#Workflow

name: Test Workflow


#Trigger

on : 
    push: #Matlab: Git Push → Workflow Start
        branches:
            - main
#Job   
jobs:
    test:
        runs-on: ubutnu:latest #Runner
#Step
        steps:
            - name : Print Message
              run: echo "GitHub Actions Test 2"